package Catalyst::Default::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Catalyst::Default::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=default-catalyst',
        user => 'catalyst',
        password => 'catalyst',
        AutoCommit => q{1},
    }
);

=head1 NAME

Catalyst::Default::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Catalyst::Default>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Catalyst::Default::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.54

=head1 AUTHOR

Phillip Smith

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
